version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: sistema_acesso
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
      - "9229:9229"
    command: npm run debug
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=root
      - DB_NAME=sistema_acesso
      - DB_PORT=5432
      - JWT_SECRET=secreta123
      - PORT=3000

 # frontend:
  #  build: ./frontend
   # working_dir: /app
    # volumes:
      # - ./frontend:/app
    # ports:
     # - "5173:5173"
    # command: npm run dev

volumes:
  pgdata:
