version: '3.8'

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: sistema_acesso
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    container_name: sistema-acesso-backend
    restart: always
    ports:
      - '5000:5000'
    environment:
      DATABASE_URL: postgres://postgres:root@db:5432/sistema_acesso
      JWT_SECRET: supersecret
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: sistema-acesso-frontend
    restart: always
    ports:
      - '3000:80' 
    depends_on:
      - backend

volumes:
  pgdata:
